packages:
  - packages/*

onlyBuiltDependencies:
  - '@abandonware/bluetooth-hci-socket'
  - '@abandonware/noble'
  - '@parcel/watcher'
  - '@serialport/bindings-cpp'
  - aws-sdk
  - bun
  - esbuild
  - msgpackr-extract
  - protobufjs
  - simpleble
  - usb
