CREATE INDEX "idx_users_name" ON "warehouse"."users" USING btree ("name");--> statement-breakpoint
CREATE INDEX "idx_users_email" ON "warehouse"."users" USING btree ("email");--> statement-breakpoint
CREATE INDEX "idx_messages_title" ON "warehouse"."messages" USING btree ("title");--> statement-breakpoint
CREATE INDEX "idx_devices_name" ON "warehouse"."devices" USING btree ("name");--> statement-breakpoint
CREATE INDEX "idx_device_name" ON "warehouse"."device_types" USING btree ("name");--> statement-breakpoint
CREATE INDEX "idx_device_code" ON "warehouse"."device_types" USING btree ("code");--> statement-breakpoint
CREATE INDEX "idx_addresses_street" ON "warehouse"."addresses" USING btree ("street");--> statement-breakpoint
CREATE INDEX "idx_addresses_postal_code" ON "warehouse"."addresses" USING btree ("postal_code");--> statement-breakpoint
CREATE INDEX "idx_addresses_country" ON "warehouse"."addresses" USING btree ("country");--> statement-breakpoint
CREATE INDEX "idx_tax_groups_name" ON "warehouse"."tax_groups" USING btree ("name");--> statement-breakpoint
CREATE INDEX "idx_country_code" ON "warehouse"."tax_group_coutryrates" USING btree ("country_code");--> statement-breakpoint
CREATE INDEX "idx_images_url" ON "warehouse"."images" USING btree ("url");--> statement-breakpoint
CREATE INDEX "idx_images_title" ON "warehouse"."images" USING btree ("title");--> statement-breakpoint
CREATE INDEX "idx_brands_code" ON "warehouse"."brands" USING btree ("code");--> statement-breakpoint
CREATE INDEX "idx_brands_name" ON "warehouse"."brands" USING btree ("name");--> statement-breakpoint
CREATE INDEX "idx_certificates_name" ON "warehouse"."certificates" USING btree ("name");--> statement-breakpoint
CREATE INDEX "idx_certificates_issuer" ON "warehouse"."certificates" USING btree ("issuer");--> statement-breakpoint
CREATE INDEX "idx_certificate_number" ON "warehouse"."certificates" USING btree ("certification_number");--> statement-breakpoint
CREATE INDEX "idx_notifications_title" ON "warehouse"."notifications" USING btree ("title");--> statement-breakpoint
CREATE INDEX "idx_discount_code" ON "warehouse"."discounts_v1" USING btree ("code");--> statement-breakpoint
CREATE INDEX "idx_products_name" ON "warehouse"."products" USING btree ("name");--> statement-breakpoint
CREATE INDEX "idx_products_barcode" ON "warehouse"."products" USING btree ("barcode");--> statement-breakpoint
CREATE INDEX "idx_product_labels_name" ON "warehouse"."product_labels" USING btree ("name");--> statement-breakpoint
CREATE INDEX "idx_sales_barcode" ON "warehouse"."sales" USING btree ("barcode");--> statement-breakpoint
CREATE INDEX "idx_customers_name" ON "warehouse"."customers" USING btree ("name");--> statement-breakpoint
CREATE INDEX "idx_customers_email" ON "warehouse"."customers" USING btree ("email");--> statement-breakpoint
CREATE INDEX "idx_customers_phone" ON "warehouse"."customers" USING btree ("phone");--> statement-breakpoint
CREATE INDEX "idx_customer_notes_title" ON "warehouse"."customer_notes" USING btree ("title");--> statement-breakpoint
CREATE INDEX "idx_customer_orders_barcode" ON "warehouse"."customer_orders" USING btree ("barcode");--> statement-breakpoint
CREATE INDEX "idx_customer_orders_title" ON "warehouse"."customer_orders" USING btree ("title");--> statement-breakpoint
CREATE INDEX "idx_customer_orders_description" ON "warehouse"."customer_orders" USING btree ("description");--> statement-breakpoint
CREATE INDEX "idx_catalogs_name" ON "warehouse"."catalogs" USING btree ("name");--> statement-breakpoint
CREATE INDEX "idx_catalogs_barcode" ON "warehouse"."catalogs" USING btree ("barcode");--> statement-breakpoint
CREATE INDEX "idx_suppliers_name" ON "warehouse"."suppliers" USING btree ("name");--> statement-breakpoint
CREATE INDEX "idx_suppliers_code" ON "warehouse"."suppliers" USING btree ("code");--> statement-breakpoint
CREATE INDEX "idx_supplier_contacts_name" ON "warehouse"."supplier_contacts" USING btree ("name");--> statement-breakpoint
CREATE INDEX "idx_supplier_notes_title" ON "warehouse"."supplier_notes" USING btree ("title");--> statement-breakpoint
CREATE INDEX "idx_supplier_purchases_barcode" ON "warehouse"."supplier_purchases" USING btree ("barcode");--> statement-breakpoint
CREATE INDEX "idx_documents_name" ON "warehouse"."documents" USING btree ("name");--> statement-breakpoint
CREATE INDEX "idx_documents_path" ON "warehouse"."documents" USING btree ("path");--> statement-breakpoint
CREATE INDEX "idx_documents_preview_path" ON "warehouse"."documents" USING btree ("preview_path");--> statement-breakpoint
CREATE INDEX "idx_warehouses_name" ON "warehouse"."warehouses" USING btree ("name");--> statement-breakpoint
CREATE INDEX "idx_warehouse_facilities_name" ON "warehouse"."warehouse_facilities" USING btree ("name");--> statement-breakpoint
CREATE INDEX "idx_warehouse_types_name" ON "warehouse"."warehouse_types" USING btree ("name");--> statement-breakpoint
CREATE INDEX "idx_warehouse_areas_name" ON "warehouse"."warehouse_areas" USING btree ("name");--> statement-breakpoint
CREATE INDEX "idx_warehouse_areas_barcode" ON "warehouse"."warehouse_areas" USING btree ("barcode");--> statement-breakpoint
CREATE INDEX "idx_storages_name" ON "warehouse"."storages" USING btree ("name");--> statement-breakpoint
CREATE INDEX "idx_storages_barcode" ON "warehouse"."storages" USING btree ("barcode");--> statement-breakpoint
CREATE INDEX "idx_storage_name" ON "warehouse"."storage_types" USING btree ("name");--> statement-breakpoint
CREATE INDEX "idx_storage_code" ON "warehouse"."storage_types" USING btree ("code");--> statement-breakpoint
CREATE INDEX "idx_storage_labels_name" ON "warehouse"."storage_labels" USING btree ("name");--> statement-breakpoint
CREATE INDEX "idx_storage_conditions_name" ON "warehouse"."storage_conditions" USING btree ("name");--> statement-breakpoint
CREATE INDEX "idx_organizations_name" ON "warehouse"."organizations" USING btree ("name");--> statement-breakpoint
CREATE INDEX "idx_organizations_slug" ON "warehouse"."organizations" USING btree ("slug");--> statement-breakpoint
CREATE INDEX "idx_organizations_uid" ON "warehouse"."organizations" USING btree ("uid");--> statement-breakpoint
ALTER TABLE "warehouse"."brands" ADD CONSTRAINT "brands_code_unique" UNIQUE("code");